Repository ienokado/debayashi-koreyashi, pull requests merged in 2020-03, with the labels that each got.

#58 requestログの書き出しはでばやし検索処理のときのみにする
  src/app/Http/Kernel.php
  src/app/Http/Middleware/RequestLogger.php
  src/config/logging.php
  src/routes/web.php
Labels: back-end

#59 Sentryでのエラー通知設定
  README.md
  src/.env.circleci
  src/.env.example
  src/app/Exceptions/Handler.php
  src/composer.json
  src/composer.lock
  src/config/logging.php
  src/config/sentry.php
Labels: back-end

#60 トップ画面 漫才師イメージのレイアウト調整
  src/public/css/app.css
  src/public/images/top/female.svg
  src/public/images/top/male.svg
  src/resources/sass/_comedian.scss
  src/resources/sass/_search.scss
  src/resources/sass/_top-animation.scss
  src/resources/sass/_top.scss
  src/resources/sass/_variables.scss
  src/resources/views/search/index.blade.php
  src/resources/views/top.blade.php
Labels: front-end

#61 本番環境でのHTTPS通信化
  src/routes/web.php
Labels: back-end

#63 再生ボタンをアートワーク上に配置
  src/public/css/app.css
  src/resources/sass/_search.scss
  src/resources/sass/_variables.scss
  src/resources/views/search/index.blade.php
Labels: front-end

#64 プレビューボタンのレイアウト修正
  src/public/css/app.css
  src/resources/sass/_search.scss
  src/resources/views/search/index.blade.php
Labels: front-end

#65 TOPレイアウトの調整
  src/public/css/app.css
  src/resources/sass/_comedian.scss
Labels: front-end

#55 スマホ表示のみに設定
  src/app/Http/Controllers/Controller.php
  src/app/Http/Middleware/RequestLogger.php
  src/composer.json
  src/composer.lock
  src/config/app.php
Labels: back-end

#69 GoogleAnalyticsのタグを追加
  src/resources/views/common/head.blade.php
Labels: front-end

#70 GoogleAdsenseタグを追加
  src/resources/views/common/head.blade.php
Labels: front-end

#71 PCブラウザエラー画面のレイアウト調整
  src/app/Exceptions/Handler.php
  src/app/Exceptions/OnlyMobileException.php
  src/app/Http/Controllers/Controller.php
  src/public/css/app.css
  src/public/images/error/microphone.svg
  src/public/images/error/question.svg
  src/resources/sass/_only_mobile.scss
  src/resources/sass/app.scss
  src/resources/views/errors/only_mobile.blade.php
Labels: front-end

#73 トップ画面のレイアウト修正(iPhone8)
  src/public/css/app.css
  src/resources/sass/_comedian.scss
  src/resources/sass/_variables.scss
Labels: front-end

#74 アートワーク画像のサイズ調整
  src/public/css/app.css
  src/resources/sass/_search.scss
  src/resources/views/common/head.blade.php
  src/resources/views/search/index.blade.php
Labels: front-end

#77 Spotify検索結果をDB保存する
  src/app/Http/Controllers/DebayashiSearchController.php
  src/app/Models/Debayashi.php
  src/app/Models/SpotifyInfo.php
  src/database/migrations/2020_02_13_164155_create_spotify_info_table.php
  src/resources/views/search/index.blade.php
Labels: back-end

#76 AppleMusic検索結果をDB保存する
  src/app/Facades/AppleMusicFacade.php
  src/app/Http/Controllers/DebayashiSearchController.php
  src/app/Models/AppleMusicInfo.php
  src/app/Models/Debayashi.php
  src/database/migrations/2020_02_13_164244_create_apple_music_info_table.php
  src/resources/views/search/index.blade.php
Labels: back-end

#79 AppleMusic検索時"&"の文字列は"and"に変換
  src/app/Http/Controllers/DebayashiSearchController.php
  src/database/csv/debayashis.csv
  src/resources/views/search/index.blade.php
Labels: back-end

#80 Coverage設定追加
  .circleci/config.yml
  src/phpunit.xml
Labels: tuning

#81 READMEにバッジを表示
  README.md
Labels: documentation

#82 acornの脆弱性回避対応（バージョンアップ）
  src/package-lock.json
  src/package.json
Labels: front-end

#83 package.jsonの更新
  src/package-lock.json
  src/package.json
Labels: front-end

#85 タイムゾーンを日本時間に修正
  src/.env.circleci
  src/.env.example
  src/config/app.php
Labels: back-end

#86 シェアボタン の修正対応
  src/resources/views/search/index.blade.php
Labels: front-end

#87 シェアボタンのコメント修正
  src/app/Http/Controllers/DebayashiSearchController.php
  src/config/const.php
  src/resources/views/search/index.blade.php
Labels: back-end

#88 Update README.md
  README.md
Labels: documentation

#89 メタタグキーワードの設定
  src/.env.circleci
  src/.env.example
  src/config/app.php
  src/resources/views/common/head.blade.php
Labels: front-end

#90 メタタグの修正
  src/.env.circleci
  src/.env.example
  src/config/app.php
  src/resources/views/common/head.blade.php
Labels: front-end

#91 芸人検索のキーワードのログ情報を変更
  src/app/Http/Middleware/RequestLogger.php
Labels: back-end

#93 Update Robots.txt
  src/public/robots.txt
Labels: tuning

#94 GoogleAdsenseタグを再び有効に
  src/resources/views/common/head.blade.php
Labels: tuning

#97 管理画面のログイン認証/リクエストログを追加
  src/.env.circleci
  src/.env.example
  src/app/Exceptions/Handler.php
  src/app/Http/Controllers/Admin/Auth/LoginController.php
  src/app/Http/Controllers/Admin/DebayashiController.php
  src/app/Http/Controllers/Admin/LogController.php
  src/app/Http/Controllers/Admin/TopController.php
  src/app/Http/Kernel.php
  src/app/Http/Middleware/GenerateMenus.php
  src/app/Models/AdminUser.php
  src/app/Providers/RouteServiceProvider.php
  src/composer.json
  src/composer.lock
  src/config/app.php
  src/config/auth.php
  src/config/session.php
  src/database/migrations/2020_03_22_221311_create_admin_users_table.php
  src/public/assets/static/images/bg.jpg
  src/public/assets/static/images/logo.png
  src/public/assets/static/images/logo.svg
  src/public/robots.txt
  src/resources/views/admin/404.blade.php
  src/resources/views/admin/500.blade.php
  src/resources/views/admin/auth/login.blade.php
  src/resources/views/admin/blank.blade.php
  src/resources/views/admin/layout/footer.blade.php
  src/resources/views/admin/layout/layout.blade.php
  src/resources/views/admin/layout/sideBar.blade.php
  src/resources/views/admin/layout/topBar.blade.php
  src/resources/views/admin/log/index.blade.php
  src/resources/views/admin/top.blade.php
  src/routes/admin.php
Labels: back-end, front-end

#98 管理ユーザーのデータ追加説明
  README.md
Labels: documentation

#99 管理画面はPCでもみれるように
  src/app/Http/Controllers/Controller.php
Labels: back-end

#100 管理画面のTOPページがPCで見れない
  src/app/Http/Controllers/Controller.php
Labels: back-end

#101 出囃子一覧と出囃子登録機能
  src/app/Http/Controllers/Admin/DebayashiController.php
  src/app/Http/Controllers/Admin/LogController.php
  src/app/Http/Controllers/Admin/TopController.php
  src/resources/views/admin/debayashi/edit.blade.php
  src/resources/views/admin/debayashi/index.blade.php
  src/resources/views/admin/layout/layout.blade.php
  src/resources/views/admin/layout/topBar.blade.php
  src/resources/views/admin/top.blade.php
  src/routes/admin.php
Labels: back-end, front-end

#102 芸人一覧と芸人登録機能
  src/app/Http/Controllers/Admin/ComedianGroupController.php
  src/app/Http/Middleware/GenerateMenus.php
  src/resources/views/admin/comedian_group/edit.blade.php
  src/resources/views/admin/comedian_group/index.blade.php
  src/routes/admin.php
Labels: back-end

#104 robots.txtを更新（Adsenseを許可できるよう）
  src/public/robots.txt
Labels: tuning

#103 プレビューURLが取得出来る場合のみプレビューボタン生成
  src/resources/views/search/index.blade.php
Labels: front-end

#109 芸人登録処理の修正
  src/app/Http/Controllers/Admin/ComedianGroupController.php
  src/app/Http/Controllers/Admin/DebayashiController.php
  src/resources/views/admin/comedian_group/edit.blade.php
Labels: bug

#110 AppleMusic検索結果判定を修正
  src/app/Facades/AppleMusicFacade.php
Labels: bug
