Repository ienokado/debayashi-koreyashi, pull requests merged in 2020-02, with the labels that each got.

#4 Update README.md
  README.md
Labels: tuning

#7 TOP画像の追加、copyrightの追加とfavicon追加
  src/public/css/app.css
  src/public/favicon.ico
  src/public/images/top/microphone.svg
  src/resources/sass/_comedian.scss
  src/resources/sass/_logo.scss
  src/resources/sass/_search.scss
  src/resources/sass/_top-animation.scss
  src/resources/sass/app.scss
  src/resources/views/common/footer.blade.php
  src/resources/views/layouts/app.blade.php
  src/resources/views/search/index.blade.php
  src/resources/views/top.blade.php
Labels: front-end

#9 top画面にアニメーション追加
  src/public/css/app.css
  src/resources/sass/_top-animation.scss
  src/resources/views/top.blade.php
Labels: front-end

#10 検索結果画面のデザイン実装
  src/public/css/app.css
  src/public/images/search/logo-apple-music.svg
  src/public/images/search/logo-spotify.svg
  src/resources/sass/_footer.scss
  src/resources/sass/_search-animation.scss
  src/resources/sass/_search.scss
  src/resources/sass/app.scss
  src/resources/views/search/index.blade.php
  src/resources/views/top.blade.php
Labels: front-end

#14 Update README.md
  README.md
Labels: documentation

#13 SpotifyAPIの処理とOGPの設定
  src/.env.circleci
  src/.env.example
  src/app/Facades/SpotifyService.php
  src/app/Http/Controllers/DebayashiSearchController.php
  src/app/Models/Debayashi.php
  src/app/Providers/AppServiceProvider.php
  src/app/Services/SpotifyService.php
  src/composer.json
  src/composer.lock
  src/config/app.php
  src/config/const.php
  src/config/services.php
  src/public/apple-touch-icon.png
  src/public/ogp.png
  src/resources/views/common/head.blade.php
  src/resources/views/search/index.blade.php
Labels: back-end

#18 Update PULL_REQUEST_TEMPLATE.md
  PULL_REQUEST_TEMPLATE.md
Labels: documentation

#17 検索結果なしの場合の画面レイアウト調整
  src/public/css/app.css
  src/resources/sass/_search.scss
  src/resources/sass/app.scss
  src/resources/views/search/index.blade.php
Labels: front-end

#20 SpotifyAPIの設定方法を追記
  README.md
Labels: documentation

#21 Spotifyで取得情報がない場合の制御追加
  src/resources/views/search/index.blade.php
Labels: front-end

#32 芸人データのスクレイピングコマンドを設定
  README.md
  src/app/Console/Commands/ComedianGroupsScraping.php
  src/app/Http/Controllers/Api/DebayashiController.php
  src/database/csv/comedian_groups.csv
Labels: back-end

#33 初回表示のみTOPのアニメーションを動作させる
  src/app/Http/Controllers/Controller.php
  src/app/Http/Controllers/TopController.php
  src/config/const.php
  src/public/css/app.css
  src/resources/sass/_top-animation.scss
  src/resources/views/layouts/app.blade.php
  src/resources/views/top.blade.php
Labels: back-end, front-end

#37 コンビ名, アーティスト名, 曲名の長い時のレイアウト調整
  src/public/css/app.css
  src/resources/sass/_search.scss
  src/resources/views/search/index.blade.php
Labels: front-end

#40 フッターをスクロールの最後に表示させる
  src/public/css/app.css
  src/resources/sass/_footer.scss
  src/resources/sass/app.scss
  src/resources/views/common/footer.blade.php
  src/resources/views/layouts/app.blade.php
  src/resources/views/search/index.blade.php
  src/resources/views/top.blade.php
Labels: front-end

#41 Spotifyで取得した画像のサイズ調整
  src/public/css/app.css
  src/resources/sass/_search.scss
  src/resources/views/search/index.blade.php
Labels: front-end

#45 Feature/34/search result animation
  src/public/css/app.css
  src/resources/sass/_search-animation.scss
  src/resources/sass/_search.scss
  src/resources/sass/app.scss
  src/resources/views/layouts/app.blade.php
  src/resources/views/search/index.blade.php
Labels: front-end

#47 fontawesomeの読み込み箇所を変更
  src/public/css/app.css
  src/resources/sass/app.scss
  src/resources/views/common/head.blade.php
  src/resources/views/layouts/app.blade.php
  src/resources/views/top.blade.php
Labels: front-end

#49 Apple Music検索処理の追加
  src/.env.circleci
  src/.env.example
  src/app/Facades/AppleMusicFacade.php
  src/app/Facades/SpotifyFacade.php
  src/app/Http/Controllers/DebayashiSearchController.php
  src/app/Providers/AppServiceProvider.php
  src/app/Services/AppleMusicService.php
  src/composer.json
  src/composer.lock
  src/config/app.php
  src/resources/views/search/index.blade.php
Labels: back-end

#50 Update README.md
  README.md
Labels: documentation

#51 SNSシェアボタン用コメントの設定
  src/app/Http/Controllers/DebayashiSearchController.php
  src/config/const.php
  src/resources/views/search/index.blade.php
Labels: back-end

#48 トップ画面　レスポンシブ対応
  src/public/css/app.css
  src/resources/sass/_comedian.scss
  src/resources/sass/_logo.scss
  src/resources/sass/_placeholder.scss
  src/resources/sass/_top.scss
  src/resources/sass/_variables.scss
  src/resources/sass/app.scss
  src/resources/views/common/head.blade.php
  src/resources/views/top.blade.php
Labels: front-end

#53 トップ画面 スマホレイアウト修正
  src/public/css/app.css
  src/resources/sass/_comedian.scss
  src/resources/sass/_footer.scss
  src/resources/sass/_placeholder.scss
  src/resources/sass/_search.scss
  src/resources/sass/_top.scss
  src/resources/sass/_ui-common.scss
  src/resources/sass/_variables.scss
  src/resources/sass/app.scss
  src/resources/views/common/footer.blade.php
  src/resources/views/common/head.blade.php
  src/resources/views/top.blade.php
Labels: front-end

#54 検索結果画面のレスポンシブ対応
  src/public/css/app.css
  src/resources/sass/_search.scss
  src/resources/sass/_variables.scss
  src/resources/views/search/index.blade.php
Labels: front-end

#56 実機でのレイアウト修正
  src/public/css/app.css
  src/public/images/top/microphone.svg
  src/public/images/top/serif.svg
  src/resources/sass/_comedian.scss
  src/resources/sass/_search.scss
  src/resources/sass/_top.scss
  src/resources/views/layouts/app.blade.php
  src/resources/views/search/index.blade.php
Labels: front-end

#57 芸人検索時の入力キーワードをログに残す
  src/app/Http/Kernel.php
  src/app/Http/Middleware/RequestLogger.php
  src/config/const.php
Labels: back-end
